parameters:
#    ts_bodega.example.class: TS\BodegaBundle\Example

services:
#    ts_bodega.example:
#        class: %ts_bodega.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
